config/routes.rb
Rails.application.routes.draw do
  root "karacagida#index"
  get "/about_us", to: "karacagida#about_us"
  get "/certificates", to: "karacagida#certificates"
  get "/production", to: "karacagida#production"
  get "/products", to: "karacagida#products"
  get "/products/:product_name", to: "products#show"
  get "/social_contribution", to: "karacagida#socialcont"
  get "/contacts", to: "contacts#new"
  post "/contacts", to: "contacts#create"
  get "/admin", to: "admin#index"
  post "/admin", to: "admin#upload"
  delete "/admin/:certificate", to: "admin#destroy"
  get "/language/:lang", to: "language#change_locale", as: "language"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Karacagida Iletisim Formu",
      :to => "info@karacagida.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	def index
	end

	def upload
		uploaded_certificate = params[:certificate]
		title_tag = params[:certificate_name]
		file_name = title_tag.split(" ").join("_") + "."
		extension = uploaded_certificate.content_type.split("/").last
		File.open(Rails.root.join('public', 'uploads', file_name + extension), 'wb') do |file|
    	file.write(uploaded_certificate.read)
		end

		redirect_to "/admin"
  end

	def destroy
		route_to_certificates = "public/uploads/"
		certificate_to_delete = route_to_certificates + params[:certificate].split("+").join(".")
		File.delete(certificate_to_delete) if File.exist?(certificate_to_delete)

		redirect_to "/admin"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  I18n.available_locales = [:en, :tr]

  before_action :set_locale
  def set_locale
    if cookies[:educator_locale] && I18n.available_locales.include?(cookies[:educator_locale].to_sym)
      l = cookies[:educator_locale].to_sym
    else
      l = I18n.default_locale
      cookies.permanent[:educator_locale] = l
    end
    I18n.locale = l
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Mesajınız yetkililere ulaştı. En kısa zamanda sizinle telefon veya elektronik posta yoluyla iletişime geçecek.'
    else
      flash.now[:error] = 'Bir hata oluştu. Lütfen tekrar deneyiniz.'
      render :new
    end
  end
end

app/controllers/karacagida_controller.rb
class KaracagidaController < ApplicationController

	def about_us
		render :about_us
	end

	def certificates
		render :certificates
	end

	def production
		render :production
	end

	def products
		@products = all_products
		render :products
	end

	def socialcont
		render :socialcont
	end

	private

	def all_products
		PRODUCTS
	end

end

app/controllers/language_controller.rb
class LanguageController < ApplicationController
  def change_locale
    l = params[:lang].to_s.strip.to_sym
    l = I18n.default_locale unless I18n.available_locales.include?(l)
    cookies.permanent[:educator_locale] = l
    redirect_to request.referer || root_url
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def show
		@product = product
		render :show
	end

	private

	def product
		PRODUCTS.fetch(product_slug)
	end

	def product_slug
		params[:product_name]
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/karacagida_helper.rb
module KaracagidaHelper
end

app/views/admin/index.html.erb
<h1> Admin Sayfasi </h1>

<h4>
	<span>
		Websitesindeki sertifikalari bu sayfadan yeni sertifika yukleyerek degistirebilirsiniz.
		Sertifika adi websitesinde goruntulenecektir.
		Lutfen sertifikalari pdf olarak yuklemeyiniz.
	 </span>
</h4>

<div style="display:flex; width: 80%; margin-bottom: 20px;">
  <%= Dir.foreach('public/uploads/').with_index do |certificate, i| %>
    <% next if certificate == '.' || certificate == '..' %>
		<% image_source = image_path "/uploads/#{certificate}" %>
		<% certificate_to_delete = certificate.split(".").join("+") %>

		<div>
			<%= form_tag("/admin/#{certificate_to_delete}", method: :delete, id: "delete_form") do %>
			<%= submit_tag "Sil", class: "btn btn-primary delete_button"%>
			<% end %>

	    <img
	      id="<%= "#{i}" %>" src="<%= image_source %>"
	      width="240" height="320" alt="<%= certificate.split(".").first %>"
	      style="margin-right:20px;"
	    	/>
		</div>
  <% end %>

</div>

<%= form_tag({action: :upload}, multipart: true) do %>
  <%= file_field_tag 'certificate' %>
	</br>
	<%= text_field_tag 'certificate_name', "Sertifika adi"%>
	<%= submit_tag "Yukle", class: "btn btn-primary" %>
<% end %>

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div style="width: 70%;">
  <%= form_tag "/contacts" do %>
		<h4><label for="contact_name"><%= t('contact_us.title.form_name_surname')%></label></h4>
    <div class="input string required contact_name">
      <input class="string required form-control" required="required" aria-required="true" placeholder="<%= t('contact_us.placeholder.form_name_surname')%>" type="text" name="contact[name]" id="contact_name">
    </div>
		<h4><label for="contact_email"><%= t('contact_us.title.form_email')%></label></h4>
		<div class="input email required contact_email">
      <input class="string email required form-control" required="required" aria-required="true" placeholder="<%= t('contact_us.placeholder.form_email')%>" type="email" name="contact[email]" id="contact_email">
    </div>
		<h4><label for="contact_message"><%= t('contact_us.title.form_message')%></label></h4>
		<div class="input text required contact_message">
      <textarea class="text required form-control" required="required" aria-required="true" placeholder="<%= t('contact_us.placeholder.form_message')%>" name="contact[message]" id="contact_message"></textarea>
    </div>
    <div>
      <br>
      <input type="submit" name="commit" value="<%= t('contact_us.title.form_submit')%>" class="btn btn-primary" data-disable-with="Gönder">
    </div>
  <% end %>
</div>

app/views/karacagida/about_us.html.erb
<h2><%= t('about_us.title') %></h2>
<div class="about-us wrapper">
  <div class="about-us images">
    <img src="<%= asset_url('about-us/1.jpg')%>" width="340" height="248"
    style="margin-right: 30px; border:5px solid #E0F5F8">
    <img src="<%= asset_url('about-us/2.jpg')%>" width="340" height="248"
    style="margin-left: 30px; border:5px solid #E0F5F8">
  </div>
  <h4>
   <%= t('about_us.info') %>
  </h4>
</div>

app/views/karacagida/certificates.html.erb
<div>
  <%= Dir.foreach('public/uploads/').with_index do |certificate, i| %>
    <% next if certificate == '.' || certificate == '..' %>
    <a class="pop-up" href="" rel="lightbox[cert]">
      <img
        id="<%= "#{i}" %>" src=" <%= image_path "/uploads/#{certificate}" %>"
        width="240" height="320" alt="<%= certificate.split(".").first %>"
        style="margin-right:20px;margin-bottom:20px"
        />
    </a>
  <% end %>
</div>

<div class="modal" id="imagemodal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      </div>
      <div class="modal-body" style="text-align: center;">
        <img src="" id="imagepreview" style="width: 550px; height: 800px;" />
      </div>
    </div>
  </div>
</div>

app/views/karacagida/index.html.erb
<div class="homepage">
	<img src="<%= asset_url("logos/#{t('logo.image_tag')}")%>" title="Karaca Gıda"
	alt="Karaca Gıda"/>
	<img class="homepage__image" src="<%= asset_url('m.jpg')%>" title="Karaca Gıda"
	alt="Karaca Gıda"/>
</div>

app/views/karacagida/production.html.erb
<h2><%= t('production.title') %></h2>
<div class="production wrapper">
  <div class="production images">
    <img src="<%= asset_url('production/4.jpg')%>" width="340" height="510" style="margin-right:30px; border:5px solid #E0F5F8">
    <img src="<%= asset_url('production/3.jpg')%>" width="340" height="510" style="margin-left:30px; border:5px solid #E0F5F8">
  </div>
  <h4>
    <%= t('production.info') %>
  </h4>
</div>

app/views/karacagida/products.html.erb
<h2>Ürünler</h2>
<div style="display:flex; flex-wrap: wrap;">
	<% @products.each do |product| %>
	<div class="product">
		<a href="<%= "products/#{product.last.fetch("product_name")}" %>">
		<h4><%= t("products.#{product.last.fetch("product_name")}") %></h4>
		<img src="<%= asset_url("#{product.last.fetch("image_path")}")%>" width="250" height="250" alt=product.last.fetch("product_name") />
		</a>
	</div>
	<% end %>
</div>

app/views/karacagida/socialcont.html.erb
<h2><%= t('social_responsibility.title') %></h2>
<div class="socialcontribution wrapper">
	<div class="socialcontribution images">
		<img src="<%= asset_url('social-contribution/3.jpg')%>" width="320" height="240" alt="Karaca Gıdadan Eğitime Destek" title="Karaca Gıdadan Eğitime Destek" style="float:left;margin:0 20px 20px 0;border:5px solid #DFF3FF">
		<img src="<%= asset_url('social-contribution/2.jpg')%>" width="320" height="240" alt="Karaca Gıdadan Eğitime Destek" title="Karaca Gıdadan Eğitime Destek" style="float:left;margin:0 20px 20px 0;border:5px solid #DFF3FF">
		<img src="<%= asset_url('social-contribution/1.jpg')%>" width="320" height="240" alt="Karaca Gıdadan Eğitime Destek" title="Karaca Gıdadan Eğitime Destek" style="float:left;margin:0 10px 10px 0;border:5px solid #DFF3FF">
	</div>

	<h4>
		<%= t('social_responsibility.info') %>
	</h4>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Karacagida</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid">
    <nav>
      <h4>
      <ul class="nav nav-tabs" style="margin-left: 15%;">
        <li><a role="presentation" href="/"><%= t('navbar.main_page') %></a></li>
        <li><a role="presentation" href="/about_us"><%= t('navbar.about_us') %></a></li>
        <li><a role="presentation" href="/certificates"><%= t('navbar.certificates') %></a></li>
        <li><a role="presentation" href="/products"><%= t('navbar.products') %></a></li>
        <li><a role="presentation" href="/production"><%= t('navbar.production') %></a></li>
        <li><a role="presentation" href="/social_contribution"><%= t('navbar.social_responsibility') %></a></li>
        <li><a role="presentation" href="/contacts"><%= t('navbar.contact_us') %></a></li>
        <h5><li><a href="<%= language_path(:tr) %>">TR</a>|<a href="<%= language_path(:en) %>">EN</a></li></h5>
      </ul>
    </h4>
    </nav>

    <div class="row">
      <div class="col-md-2 side-nav">
        <ul class="nav nav-pills nav-stacked">
          <li><h4><%= t('products.title') %></h4></li>
          <li><a href="/products/mine-1"><%= t('products.mine-1') %></a></li>
          <li><a href="/products/mine-2"><%= t('products.mine-2') %></a></li>
          <li><a href="/products/mine-3"><%= t('products.mine-3') %></a></li>
          <li><a href="/products/altin-petek"><%= t('products.altin-petek') %></a></li>
          <li><a href="/products/petekli-kornet"><%= t('products.petekli-kornet') %></a></li>
          <li><a href="/products/kucuk-lale"><%= t('products.kucuk-lale') %></a></li>
          <li><a href="/products/buyuk-lale"><%= t('products.buyuk-lale') %></a></li>
          <li><a href="/products/sarma-kornet"><%= t('products.sarma-kornet') %></a></li>
          <li><a href="/products/end-sarma-kornet"><%= t('products.end-sarma-kornet') %></a></li>
          <li><a href="/products/kup-recellik"><%= t('products.kup-recellik') %></a></li>
          <li><a href="/products/kagit-helva"><%= t('products.kagit-helva') %></a></li>
        </ul>
      </div>

      <div class="col-md-10 main">
        <%= yield %>
      </div>
    </div>

    <footer class="navbar-fixed-bottom footer-distributed">
			<div class="footer-left footer-div">
				<img src="<%= asset_url('logos/karaca.png')%>"></img>
				<p class="footer-company-name">Karacagida Ltd © 2017</p>
			</div>

			<div class="footer-right footer-div">
				<div class="footer-div-content">
          <img src="<%= asset_url('logos/pin.png')%>"><img>
					<p class="footnote-text"> Kemalpaşa Yolu 5. Km Çınarköy Kemalpaşa / İzmir</p>
				</div>
				<div class="footer-div-content">
          <img src="<%= asset_url('logos/phone.png')%>"><img>
					<p class="footnote-text">t: +90 232 878 90 60 (pbx) </br> f: +90 232 878 92 34 </p>
				</div>
				<div class="footer-div-content">
          <img src="<%= asset_url('logos/email.png')%>"><img>
					<p class="footnote-text"><a href="mailto:info@karacagida.com">info@karacagida.com</a></p>
				</div>
			</div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/products/show.html.erb
<div style="margin:50px;">
	<div>
		<h4><%= t("products.#{@product.fetch("product_name")}") %></h4>
		<img src="<%= asset_url("#{@product.fetch("image_path")}")%>" width="400" height="400" alt="<%= @product.fetch("product_name") %>" />
		<h4><%= "#{t('product_amount.text')} #{@product.fetch("amount")} #{t('product_amount.box')}"%></h4>
	</div>
</div>